production:
  adapter: sqlite3
  encoding: utf8
  database: db/pms_production.sqlite3
  timeout: 5000  

development:
  adapter: sqlite3
  encoding: utf8
  database: db/pms_development.sqlite3
  timeout: 5000

test:
  adapter: sqlite3
  encoding: utf8
  database: db/pms_test.sqlite3
  timeout: 5000
